host: '172.18.0.1'
port: 8848
namespace: 'ba63c7bc-827d-49fb-9d56-0cbf184c420c'
user: 'nacos'
password: 'nacos'
dataid: 'user_srv.json'
group: 'dev'
# name: 'user_srv'
# mysql:
#   host: '127.0.0.1'
#   port: 3306
#   user: 'root'
#   password: 'root'
#   db: 'shop_user_srv'
# consul:
#   host: '172.18.0.1'
#   port: 8500  