host: '172.18.0.1'
port: 8848
namespace: '16d89312-79dd-41c5-9a2a-7e07d9cadf2d'
user: 'nacos'
password: 'nacos'
dataid: 'goods_web.json'
group: 'dev'

# name: 'user-web'
# port: 9023

# goods_srv:
#   # host: "127.0.0.1"  #直接通过name去consul获取
#   # port: 50051 
#   name: 'goods_srv'

# jwt:
#   key: 'KuKRu_%9}&GfG-ggdN[c@6w%?dMDC(Wn'
  
# sms:
#   key: ''
#   secrect: ''
#   expire: 300

# redis:
#   host: '127.0.0.1'
#   port: '6379'

# consul:
#   host: '127.0.0.1'
#   port: '8500'